# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.0677e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3733e-14, 6.4069e+02, 4.3066e+21],
        [1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8405, 0.3487, 0.2191],
        [0.9182, 0.9243, 0.8462],
        [0.4862, 0.8147, 0.0877],
        [0.1089, 0.0592, 0.2063],
        [0.5810, 0.5165, 0.8710]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [12]:
x[0][1] = 2
print(x)

tensor([[2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4862, 0.8147, 0.0877],
        [0.1089, 2.0000, 0.2063],
        [0.5810, 0.5165, 0.8710]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [94]:
a = torch.Tensor(2,17)
print(a)

b = torch.FloatTensor(3,1)
print(b)

c = torch.LongTensor(5,2,1)
print(c)

d = torch.full((5,2,1),7)
print(d)

e = torch.zeros(5).byte()
print(e)
e[1:4] = 1
print(e)

tensor([[ 1.0703e-35,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  1.7092e-35,  0.0000e+00,  4.0646e-36,
          0.0000e+00, -7.2091e-19],
        [ 4.5600e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
tensor([[3.3825e-35],
        [0.0000e+00],
        [2.3694e-38]])
tensor([[[          100290432],
         [                 78]],

        [[                  0],
         [                  0]],

        [[       450971566080],
         [8319683848551211643]],

        [[3180222411935070754],
         [8391722768137527840]],

        [[7959390389040738153],
         [2318282025317573236]]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [105]:
y = torch.rand(5, 3)
print(x + y)

tensor([[2.0914, 2.7412, 2.5643],
        [2.4846, 2.0685, 2.7355],
        [1.3826, 1.5990, 0.7342],
        [0.6374, 2.0926, 1.0615],
        [0.9686, 1.0214, 1.5012]])


### 2.2 Addition: syntax 2

In [106]:
print(torch.add(x, y))

tensor([[2.0914, 2.7412, 2.5643],
        [2.4846, 2.0685, 2.7355],
        [1.3826, 1.5990, 0.7342],
        [0.6374, 2.0926, 1.0615],
        [0.9686, 1.0214, 1.5012]])


### 2.3 Addition: giving an output tensor

In [107]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[2.0914, 2.7412, 2.5643],
        [2.4846, 2.0685, 2.7355],
        [1.3826, 1.5990, 0.7342],
        [0.6374, 2.0926, 1.0615],
        [0.9686, 1.0214, 1.5012]])


### 2.4 Addition: in-place

adds `x`to `y`

In [108]:
y.add_(x)
print(y)

tensor([[2.0914, 2.7412, 2.5643],
        [2.4846, 2.0685, 2.7355],
        [1.3826, 1.5990, 0.7342],
        [0.6374, 2.0926, 1.0615],
        [0.9686, 1.0214, 1.5012]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [109]:
print(x[:, 1])

tensor([2.0000, 2.0000, 0.8147, 2.0000, 0.5165])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [153]:
# 1)
a = torch.full((4,1),2)
b = torch.full((4,1),5)
print(a)
print(b)
print(torch.multiply(a,b))
# 2)
print(b.multiply_(a))
print(b)
# 3)
print(torch.divide(a,b))
# 4)
a = torch.randn(2,4)
b = torch.randn(4,2)
print(torch.matmul(a,b))

tensor([[2],
        [2],
        [2],
        [2]])
tensor([[5],
        [5],
        [5],
        [5]])
tensor([[10],
        [10],
        [10],
        [10]])
tensor([[10],
        [10],
        [10],
        [10]])
tensor([[10],
        [10],
        [10],
        [10]])
tensor([[0.2000],
        [0.2000],
        [0.2000],
        [0.2000]])
tensor([[ 0.4932, -3.0942],
        [-2.4091,  0.5171]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [154]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [155]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [156]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [157]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [159]:
a = torch.ones(5,2)
print(a)
b = a.numpy()
print(b)
c = torch.from_numpy(b)
print(c)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [161]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
